baseURL = 'https://moneywisesidehustler.tripwiretech.com/'
languageCode = 'en-us'
title = 'Money-Wise Side Hustler Blog'
theme = 'blist'
metaDataFormat = "yaml"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Chelsea Suddens"
      introSubtitle = "A mother to a young boy and another due September (2 under 2). Sharing our journey of building various income streams to achieve a goal of financial freedom by 2032. All while balancing increasing costs of living, full time employment and family life."
      introPhoto = "/intro.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "pages/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Money-Wise Side Hustler · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  instagram = "https://www.instagram.com/curlingcharlz/"
  youtube = "https://www.youtube.com/channel/UCfrcL4MPzcKguuREEQfEkOA"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
